
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("random_number_test");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview = new global::Gtk.TextView();
		this.textview.CanFocus = true;
		this.textview.Name = "textview";
		this.textview.Editable = false;
		this.textview.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add(this.textview);
		this.Add(this.GtkScrolledWindow);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.textview.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnSizeAllocated);
	}
}
